services:
  apache:
    image: httpd:latest
    container_name: tls-configurator-apache
    ports:
      - "8282:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs
      - ./demo-crt:/usr/local/apache2/certificates
      - ./install.sh:/usr/local/apache2/install.sh:rwx
